### ISSUE TITLE
links from arxiv

### ISSUE THREAD

**Issue by harrow** [scirate/scirate#306]
Here was a question from my colleague Dirk Englund:
"I really like scirate! We’re about to put on arxiv a theory paper on boson sampling. I’m wondering if there’s a way I can include a link to the relevant scirate discussion into the arxiv paper at the point of submission (i.e., when ArXiv hasn’t yet made a link for it)? "

I think this is mostly a question for arxiv.org, and relates to their trackback policy.  Any ideas about what we can do on our end?

**Comment by silky** [comment]
i think it would be best if, eventually, there was just a scirate link on every single arXiv paper, rather than having it opt-in by particular authors.

so i don't really see that there is anything to do from the scirate side, aside from considering asking arxiv to do that (but i think it's probably too soon). we could always do this without asking, via the arxiv's trackbacks - http://arxiv.org/help/trackback/ - but i think doing that en mass would be spam. infact this was discussed - https://github.com/scirate/scirate/issues/224 - and it turns out that, supposing @mispy did implement trackbacks being sent, then arXiv are not publishing them).
