### ISSUE TITLE
Change in arXiv TeX rendering of titles

### ISSUE THREAD

**Issue by wbrenna** [scirate/scirate#322]
It looks like titles with LaTeX in them have been subject to an arXiv-side change. They are now appearing on scirate with [_Math Processing Error_] in place of the TeX.

**Comment by silky** [comment]
Thanks for the report, can you point me at an example?

For example, this paper - https://scirate.com/arxiv/1602.06475 - is rendered fine for me.

**Comment by wbrenna** [comment]
Interestingly this behaviour has vanished and the text all renders correctly now. I had checked it on two different machines; perhaps it was just a temporary server problem on the scirate.com instance. There may be some logs as I posted very soon after noticing, but other than that I think this issue is closed!

**Comment by silky** [comment]
Sometimes what happens is the MathJax (which we use to render the maths) CDN gets corrupted coming in to your network.

So it just takes some cache reset or something to work again (either on your computer or on a network you can't control).

arXiv itself uses a different URL for MathJax than us, so that would explain why you didn't see the problem there.
