### ISSUE TITLE
deleted comments show up on activity feeds

### ISSUE THREAD

**Issue by harrow** [scirate/scirate#325]
See here for some examples.  The comments are labeled "deleted" but still show up even when not logged in as moderator.

https://scirate.com/56
https://scirate.com/56/comments
https://scirate.com/stefano-pirandola
https://scirate.com/stefano-pirandola/comments

**Comment by silky** [comment]
perhaps related to https://github.com/scirate/scirate/issues/303

**Comment by mispy** [comment]
Those comments weren't actually deleted themselves, but rather were replies to a deleted comment. I've made it handle that scenario a bit better now-- if you delete the parent comment of a thread with undeleted replies it'll show "(deleted comment)" and then the replies. (but in this particular situation, I've also just deleted the replies, since that was presumably the intent)
