### ISSUE TITLE
"tantan" is rendered as an emojii

### ISSUE THREAD

**Issue by anlucia** [scirate/scirate#396]
See the abstract and the comments in https://scirate.com/arxiv/2011.05232 and also check  https://scirate.com/search?utf8=%E2%9C%93&q=instantaneous

It seems that the text ```tantant``` is rendered as a smiley face emojii. This happens both in Firefox, Chromium, and according to the comment in Safari. I tried disabling javascript, and it is still rendered as such, so probably it is not due to Mathjax or similar. Maybe the font choice?

**Comment by silky** [comment]
wow yes; you're right, it's the font: https://fonts.google.com/?query=sen&preview.text=tantan&preview.text_type=custom

amazing discovery.

**Comment by silky** [comment]
the font issue has been slightly controversial - https://github.com/scirate/scirate/commit/a6e666a7ffa8519e81adcea2464b3563198382d3

i'm happy to change it to something that satisfies the requirements listed on that link, if anyone has any good thoughts; otherwise i'm inclined to just leave it as an easter egg.

**Comment by abhinavd** [comment]
Hi, I would like to report that this issue is more general. For example, if you click on an author's name, it searches for all papers by the author at the URL `https://scirate.com/search?q=au:<author name>`. The title of this page is generally of the form: "results for au:<author name> in:quant-ph".
When one looks at last names beginning with D or P, the current font renders them as the emojis :smile: and :stuck_out_tongue:, respectively.
Example URL: [my own profile](https://scirate.com/search?q=au:Deshpande_A+in:quant-ph).

**Comment by silky** [comment]
thanks @abhinavd - okay, that's genuinely annoying; i'll have a think about this and just pick a new font that doesn't have this problem.
